# Generated by Django 3.0.6 on 2020-06-04 23:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='approve_Exception',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=8)),
                ('comment', models.TextField(blank=True, default='Pending')),
                ('exception_id', models.IntegerField(default=0, null=True)),
                ('patch_id', models.IntegerField(default=0, null=True)),
                ('approver_id', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AUTHORIZE_TYPE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='EXCEPTION_TYPE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Patch', 'Patch'), ('Server', 'Server')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='exclude_patch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patch_id', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=30)),
                ('justification', models.TextField()),
                ('exclude_date', models.DateTimeField(default=datetime.datetime.now)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EXCEPTION',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=8)),
                ('patch_id', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=30)),
                ('justification', models.TextField()),
                ('action_plan', models.TextField()),
                ('exclude_date', models.DateTimeField(default=datetime.datetime.now)),
                ('content', models.TextField(null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exception.EXCEPTION_TYPE')),
            ],
        ),
        migrations.CreateModel(
            name='AUTHORIZE_EXCEPTION',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=8)),
                ('exception_id', models.IntegerField(null=True)),
                ('comment', models.TextField(blank=True, default='Pending')),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
