# Generated by Django 3.0.6 on 2020-05-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exception', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='approve_Exception',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=8)),
                ('comment', models.TextField(blank=True, default='Pending')),
                ('exception_id', models.IntegerField(default=0, null=True)),
                ('patch_id', models.IntegerField(default=0, null=True)),
                ('approver_id', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
