# Generated by Django 3.0.6 on 2020-07-08 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exception', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exception',
            name='risk_id',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
