# Generated by Django 3.0.6 on 2020-06-05 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exception', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authorize_type',
            old_name='type',
            new_name='kind',
        ),
        migrations.RenameField(
            model_name='exception',
            old_name='type',
            new_name='kind',
        ),
        migrations.RenameField(
            model_name='exception_type',
            old_name='type',
            new_name='kind',
        ),
    ]
