# Generated by Django 3.0.6 on 2020-06-05 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exception', '0002_auto_20200605_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exception',
            name='state',
        ),
        migrations.AlterField(
            model_name='exception',
            name='kind',
            field=models.IntegerField(null=True),
        ),
    ]
