# Generated by Django 3.0.5 on 2020-04-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exception', '0002_auto_20200426_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='exclude_patch',
            name='patch_from',
            field=models.IntegerField(null=True),
        ),
    ]
