# Generated by Django 3.0.6 on 2020-07-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exception', '0002_exception_risk_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='validate_exception',
            name='risk_id',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='authorize_type',
            name='kind',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending'), ('Canceled', 'Canceled')], max_length=8),
        ),
        migrations.AlterField(
            model_name='exception',
            name='state',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending'), ('Canceled', 'Canceled')], default='Pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='validate_exception',
            name='state',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending'), ('Canceled', 'Canceled')], default='Pending', max_length=8),
        ),
    ]
