# Generated by Django 3.0.6 on 2020-06-05 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exception', '0003_auto_20200605_0041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exception',
            old_name='kind',
            new_name='exception_type',
        ),
    ]
