# Generated by Django 3.0.6 on 2020-07-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exception', '0003_auto_20200718_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validate_exception',
            name='risk_id',
        ),
        migrations.AddField(
            model_name='validate_exception',
            name='approver_pending',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
