# Generated by Django 3.0.5 on 2020-04-27 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exception', '0003_exclude_patch_patch_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exclude_patch',
            name='patch_from',
        ),
    ]
