# Generated by Django 3.0.6 on 2020-06-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exception', '0004_auto_20200605_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='exception',
            name='state',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=8),
        ),
    ]
