# Generated by Django 3.0.6 on 2020-07-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exception', '0005_validate_exception_risk_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validate_exception',
            name='approver_pending',
            field=models.TextField(blank=True, null=True),
        ),
    ]
