# Generated by Django 3.0.6 on 2020-07-01 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exception', '0005_exception_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exception',
            name='patch_id',
            field=models.TextField(null=True),
        ),
    ]
