# Generated by Django 3.0.6 on 2020-08-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exception', '0006_auto_20200721_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='exception',
            name='status_id',
            field=models.IntegerField(null=True),
        ),
    ]
