# Generated by Django 3.0.6 on 2020-08-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exception', '0007_exception_status_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exception',
            name='status_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
