# Generated by Django 3.0.6 on 2020-07-04 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exception', '0012_validate_exception_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validate_exception',
            name='time',
        ),
    ]
