# Generated by Django 3.0.6 on 2020-07-04 04:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exception', '0013_remove_validate_exception_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='validate_exception',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
