# Generated by Django 3.0.6 on 2020-07-05 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0007_auto_20200604_0108'),
        ('exception', '0016_auto_20200704_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='exception',
            name='exception',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servers.SERVER'),
        ),
    ]
