# Generated by Django 3.0.6 on 2020-07-05 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exception', '0017_exception_exception'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exception',
            old_name='exception',
            new_name='server',
        ),
    ]
