# Generated by Django 3.0.6 on 2020-07-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exception', '0018_auto_20200705_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exception',
            name='server',
            field=models.TextField(null=True),
        ),
    ]
