# Generated by Django 3.0.6 on 2020-06-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ADVISORY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('criticality', models.CharField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], max_length=8)),
            ],
        ),
    ]
