# Generated by Django 3.0.6 on 2020-05-05 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patches', '0002_auto_20200505_2038'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='patchApproverRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approverz', to=settings.AUTH_USER_MODEL)),
                ('patch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patches.patch')),
            ],
        ),
    ]
