# Generated by Django 3.0.6 on 2020-05-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patchapproverrelationship',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
