# Generated by Django 3.0.6 on 2020-05-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorize_exception',
            name='approver',
        ),
        migrations.AddField(
            model_name='authorize_exception',
            name='approver_id',
            field=models.IntegerField(null=True),
        ),
    ]
