# Generated by Django 3.0.6 on 2020-05-26 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('approvers', '0002_auto_20200525_0735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorize_exception',
            name='approver_id',
        ),
        migrations.AddField(
            model_name='authorize_exception',
            name='approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approverAuthorize', to=settings.AUTH_USER_MODEL),
        ),
    ]
