# Generated by Django 3.0.6 on 2020-05-05 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patch',
            name='approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patch',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
