# Generated by Django 3.0.6 on 2020-08-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patches',
            name='created_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='patches',
            name='last_update_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='patches',
            name='patch_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='patches',
            name='patched_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='patches',
            name='status_id',
            field=models.IntegerField(null=True),
        ),
    ]
