# Generated by Django 3.0.6 on 2020-05-06 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patches', '0002_auto_20200505_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patch',
            name='approver',
        ),
    ]
