# Generated by Django 3.0.6 on 2020-08-03 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patches', '0002_auto_20200803_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patches',
            name='patch_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
