# Generated by Django 3.0.6 on 2020-06-02 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_server_approver_relation_server_client_relation'),
        ('patches', '0002_patches'),
    ]

    operations = [
        migrations.CreateModel(
            name='SERVER_PATCH_RELATION',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patches.PATCHES')),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servers.SERVER')),
            ],
        ),
    ]
