# Generated by Django 3.0.2 on 2020-02-24 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patches', '0002_auto_20200224_0332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patch',
            name='date',
        ),
    ]
