# Generated by Django 3.0.6 on 2020-05-09 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patches', '0003_remove_patch_approver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patch',
            old_name='user',
            new_name='client',
        ),
    ]
