# Generated by Django 3.0.6 on 2020-06-02 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patches', '0003_server_patch_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='patches',
            name='scheduled_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='patches',
            name='due_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
