# Generated by Django 3.0.6 on 2020-06-02 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patches', '0004_auto_20200602_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patches',
            name='server',
        ),
    ]
