# Generated by Django 3.0.2 on 2020-03-24 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patches', '0004_patch_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patch',
            name='user',
        ),
    ]
