# Generated by Django 3.0.6 on 2020-08-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patches', '0004_auto_20200803_0439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patches',
            name='id',
        ),
        migrations.AlterField(
            model_name='patches',
            name='patch_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
