# Generated by Django 3.0.5 on 2020-04-06 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exceptions', '0002_auto_20200406_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exclude_patch',
            name='patchFrom',
        ),
        migrations.AddField(
            model_name='exclude_patch',
            name='userID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
