# Generated by Django 3.0.5 on 2020-04-06 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patches', '0001_initial'),
        ('exceptions', '0005_auto_20200406_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exclude_patch',
            name='patchFrom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='patches.patch'),
        ),
        migrations.AlterField(
            model_name='exclude_patch',
            name='userID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
