# Generated by Django 3.0.5 on 2020-04-06 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exceptions', '0006_auto_20200406_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exclude_patch',
            name='userID',
        ),
    ]
