# Generated by Django 3.0.6 on 2020-07-07 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SERVER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=30)),
                ('os', models.CharField(max_length=30)),
                ('reboot_required', models.CharField(default='False', max_length=5)),
                ('domain', models.CharField(default='ibmcloud.dst.ibm.com', max_length=30)),
                ('ansible_id', models.CharField(max_length=50)),
                ('carbon_black', models.CharField(default='N/A', max_length=5)),
                ('crowd_strike', models.CharField(default='N/A', max_length=5)),
                ('big_fix', models.CharField(default='True', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='SERVER_USER_RELATION',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servers.SERVER')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
