# Generated by Django 3.0.6 on 2020-06-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_auto_20200602_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='ansible_id',
            field=models.CharField(max_length=50),
        ),
    ]
