# Generated by Django 3.0.6 on 2020-06-04 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0006_server_user_relation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server_client_relation',
            name='client',
        ),
        migrations.RemoveField(
            model_name='server_client_relation',
            name='server',
        ),
        migrations.RemoveField(
            model_name='server',
            name='approver',
        ),
        migrations.RemoveField(
            model_name='server',
            name='client',
        ),
        migrations.DeleteModel(
            name='SERVER_APPROVER_RELATION',
        ),
        migrations.DeleteModel(
            name='SERVER_CLIENT_RELATION',
        ),
    ]
